services:
  traefik:
    image: "traefik:v2.5"
    container_name: wp_traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Don't do this in production!
    volumes:
      - ./docker/dev/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/ssl/traefik
    networks:
      - wp_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.traefik.me`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.domains[0].main=traefik.me
      - traefik.http.routers.traefik.tls.domains[0].sans=*.traefik.me
      - traefik.http.services.traefik.loadbalancer.server.port=8080

  db:
    image: mysql:latest
    container_name: wp_mysql
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - wp_network
    environment:
      - MYSQL_ROOT_PASSWORD=wp_root
      - MYSQL_DATABASE=wp_db
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=ChangeMe
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    networks:
      - wp_network
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.traefik.me`)
      - traefik.http.routers.phpmyadmin.tls=true
      # - traefik.http.services.phpmyadmin.loadbalancer.server.port=80

  wordpress:
    image: wordpress:latest
    container_name: wp_wordpress
    restart: always
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    ports:
      - 9090:80
    networks:
      - wp_network
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wp_user
      - WORDPRESS_DB_PASSWORD=ChangeMe
      - WORDPRESS_DB_NAME=wp_db
      - WP_HOME=http://localhost/wp-front
      - WP_SITEURL=http://localhost/wp-front
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(`home.traefik.me`)
      - traefik.http.routers.wordpress.tls=true
      - traefik.http.services.wordpress.loadbalancer.server.port=80

  reverse-proxy-https-helper:
    container_name: wp_ssl_fetcher
    image: alpine
    command: sh -c "cd /etc/ssl/traefik
      && wget traefik.me/cert.pem -O cert.pem
      && wget traefik.me/privkey.pem -O privkey.pem"
    volumes:
      - certs:/etc/ssl/traefik
    networks:
      - wp_network
volumes:
  db_data:
  certs:

networks:
  wp_network:
    name: wp_network
